### ISSUE TITLE
XEVE-19-001, XEVE-19-003, XEVE-19-006

### ISSUE THREAD

**Issue by YJSoft** [daolcms/daolcms#158]

**Comment by YJSoft** [comment]
fbd64ce196d96754f4f7afa6d88ce4f34441c47a

**Comment by dorami** [comment]
0a614b9418c178dab87b69f2fc9f24cdda07cdcc

**Comment by dorami** [comment]
댓글이 있는 문서에서 오류가 발생함. 패치 연기

**Comment by dorami** [comment]
300c2e1e3c5b5d448f34207f14102648b6f867f4에서 수정됨.
