### ISSUE TITLE
XEVE-19-008, XEVE-19-009

### ISSUE THREAD

**Issue by YJSoft** [daolcms/daolcms#160]

**Comment by YJSoft** [comment]
체크리스트
- [ ] fileinfo 확장 체크여부
- [ ] 캐시파일 생성/재생성시 오류 발생여부
- [ ] 캐시파일 읽기/쓰기 정상여부

**Comment by dorami** [comment]
https://github.com/daolcms/daolcms/commit/820832964e34fc0f8eb20672f96980d2ebaa104b

**Comment by YJSoft** [comment]
캐시파일 재생성 및 캐시 정상생성 테스트 완료
